<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.13" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.13">
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.13" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.13">
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LocationService.Application\LocationService.Application.csproj" />
	</ItemGroup>

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

</Project>
