// <auto-generated />
using LocationService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocationService.Infrastructure.Migrations
{
    [DbContext(typeof(LocationDbContext))]
    partial class LocationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocationService.Domain.Entities.AdministrativeDivision", b =>
                {
                    b.Property<int>("DivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DivisionId"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("DivisionCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DivisionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int?>("ParentDivisionId")
                        .HasColumnType("int");

                    b.HasKey("DivisionId");

                    b.HasIndex("CountryId");

                    b.HasIndex("DivisionCode");

                    b.HasIndex("IsActive");

                    b.HasIndex("Level");

                    b.HasIndex("ParentDivisionId");

                    b.HasIndex("CountryId", "Level");

                    b.ToTable("AdministrativeDivisions");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<int?>("DivisionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("DivisionId");

                    b.HasIndex("IsActive");

                    b.HasIndex("NormalizedName");

                    b.HasIndex("CountryId", "IsActive");

                    b.HasIndex("NormalizedName", "CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.Continent", b =>
                {
                    b.Property<int>("ContinentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContinentId"));

                    b.Property<string>("ContinentCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ContinentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ContinentId");

                    b.HasIndex("ContinentCode")
                        .IsUnique();

                    b.HasIndex("ContinentName");

                    b.ToTable("Continents");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<int?>("ContinentId")
                        .HasColumnType("int");

                    b.Property<string>("CountryCodeAlpha2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CountryCodeAlpha3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("CountryCodeNumeric")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CountryId");

                    b.HasIndex("ContinentId");

                    b.HasIndex("CountryCodeAlpha2")
                        .IsUnique();

                    b.HasIndex("CountryCodeAlpha3")
                        .IsUnique();

                    b.HasIndex("CountryCodeNumeric")
                        .IsUnique();

                    b.HasIndex("CountryName");

                    b.HasIndex("IsActive");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.PostalCode", b =>
                {
                    b.Property<int>("PostalCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostalCodeId"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.HasKey("PostalCodeId");

                    b.HasIndex("CityId");

                    b.HasIndex("Code");

                    b.HasIndex("Code", "CityId");

                    b.ToTable("PostalCodes");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.AdministrativeDivision", b =>
                {
                    b.HasOne("LocationService.Domain.Entities.Country", "Country")
                        .WithMany("Divisions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LocationService.Domain.Entities.AdministrativeDivision", "ParentDivision")
                        .WithMany("ChildDivisions")
                        .HasForeignKey("ParentDivisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");

                    b.Navigation("ParentDivision");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.City", b =>
                {
                    b.HasOne("LocationService.Domain.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LocationService.Domain.Entities.AdministrativeDivision", "Division")
                        .WithMany("Cities")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");

                    b.Navigation("Division");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.Country", b =>
                {
                    b.HasOne("LocationService.Domain.Entities.Continent", "Continent")
                        .WithMany("Countries")
                        .HasForeignKey("ContinentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Continent");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.PostalCode", b =>
                {
                    b.HasOne("LocationService.Domain.Entities.City", "City")
                        .WithMany("PostalCodes")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.AdministrativeDivision", b =>
                {
                    b.Navigation("ChildDivisions");

                    b.Navigation("Cities");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.City", b =>
                {
                    b.Navigation("PostalCodes");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.Continent", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Divisions");
                });
#pragma warning restore 612, 618
        }
    }
}
