import 'package:flutter/material.dart';

import '../../shell/models/admin_shell_models.dart';
import 'admin_search_result.dart';

class AdminSearchCatalog {
  static const results = <AdminSearchResult>[
    AdminSearchResult(
      page: AdminShellPage.dashboard,
      title: 'Dashboard',
      description: 'View platform activity and key statistics',
      icon: Icons.dashboard_outlined,
      keywords: [
        'dashboard',
        'home',
        'homepage',
        'main page',
        'main screen',
        'overview',
        'summary',
        'platform overview',
        'platform summary',
        'statistics',
        'stats',
        'analytics',
        'insights',
        'metrics',
        'kpi',
        'kpis',
        'activity',
        'platform activity',
        'recent activity',
        'performance',
        'performance metrics',
        'usage',
        'user activity',
        'event activity',
        'total users',
        'total events',
        'total reports',
        'report statistics',
        'refund statistics',
        'revenue',
        'income',
        'earnings',
        'bookmarks',
        'likes',
        'comments',
        'engagement',
        'segments',
        'top categories',
        'top genres',
      ],
    ),
    AdminSearchResult(
      page: AdminShellPage.users,
      title: 'Users',
      description: 'View, edit, ban, and manage platform users',
      icon: Icons.people_outline_rounded,
      keywords: [
        'user',
        'users',
        'manage user',
        'manage users',
        'user management',
        'member',
        'members',
        'member management',
        'person',
        'people',
        'participant',
        'participants',
        'attendee',
        'attendees',
        'account',
        'accounts',
        'user account',
        'user accounts',
        'profile',
        'profiles',
        'user profile',
        'user profiles',
        'edit user',
        'edit users',
        'update user',
        'update users',
        'view user',
        'view users',
        'find user',
        'find users',
        'search user',
        'search users',
        'delete user',
        'delete users',
        'remove user',
        'remove users',
        'ban user',
        'ban users',
        'unban user',
        'unban users',
        'blocked user',
        'blocked users',
        'banned user',
        'banned users',
        'suspended user',
        'suspended users',
        'administrator',
        'administrators',
        'admin user',
        'admin users',
        'role',
        'roles',
        'change role',
        'user role',
        'email',
        'username',
        'password',
        'login',
        'registration',
        'registered users',
        'new users',
        'user reviews',
        'ratings',
        'rating',
      ],
    ),
    AdminSearchResult(
      page: AdminShellPage.events,
      title: 'Events',
      description: 'Create, edit, review, and manage events',
      icon: Icons.event_outlined,
      keywords: [
        'event',
        'events',
        'manage event',
        'manage events',
        'event management',
        'create event',
        'new event',
        'add event',
        'edit event',
        'edit events',
        'update event',
        'update events',
        'delete event',
        'delete events',
        'remove event',
        'remove events',
        'view event',
        'view events',
        'find event',
        'find events',
        'search event',
        'search events',
        'event details',
        'event information',
        'event organizer',
        'event organisers',
        'organizer',
        'organizers',
        'organiser',
        'organisers',
        'host',
        'hosts',
        'event host',
        'event owner',
        'venue',
        'location',
        'address',
        'map',
        'coordinates',
        'event image',
        'event cover',
        'event picture',
        'event date',
        'event time',
        'upcoming event',
        'upcoming events',
        'past event',
        'past events',
        'published event',
        'draft event',
        'cancel event',
        'cancelled event',
        'event capacity',
        'capacity',
        'availability',
        'available tickets',
        'sold out',
        'ticket',
        'tickets',
        'event ticket',
        'event tickets',
        'ticket type',
        'ticket types',
        'price',
        'prices',
        'event price',
        'free event',
        'paid event',
        'reservation',
        'reservations',
        'booking',
        'bookings',
        'event booking',
        'event reservation',
        'attendee',
        'attendees',
        'event attendee',
        'event attendees',
        'guest',
        'guests',
        'participant',
        'participants',
        'remove attendee',
        'remove attendees',
        'cancel ticket',
        'cancel tickets',
        'event comments',
        'event likes',
        'event bookmarks',
      ],
    ),
    AdminSearchResult(
      page: AdminShellPage.categories,
      title: 'Categories',
      description: 'Manage event categories and classification',
      icon: Icons.category_outlined,
      keywords: [
        'category',
        'categories',
        'manage category',
        'manage categories',
        'category management',
        'create category',
        'new category',
        'add category',
        'edit category',
        'edit categories',
        'update category',
        'delete category',
        'delete categories',
        'remove category',
        'event category',
        'event categories',
        'classification',
        'classifications',
        'taxonomy',
        'tag',
        'tags',
        'event tag',
        'event tags',
        'segment',
        'segments',
        'event segment',
        'event segments',
        'create segment',
        'edit segment',
        'delete segment',
        'genre',
        'genres',
        'event genre',
        'event genres',
        'create genre',
        'edit genre',
        'delete genre',
        'subgenre',
        'subgenres',
        'sub genre',
        'sub genres',
        'event subgenre',
        'event subgenres',
        'create subgenre',
        'edit subgenre',
        'delete subgenre',
        'event type',
        'event types',
        'topic',
        'topics',
        'group',
        'groups',
        'filter category',
        'filter categories',
      ],
    ),
    AdminSearchResult(
      page: AdminShellPage.contentModeration,
      title: 'Content moderation',
      description: 'Review reports, moderation decisions, and refunds',
      icon: Icons.gavel_outlined,
      keywords: [
        'moderation',
        'content moderation',
        'moderate',
        'moderator',
        'moderators',
        'moderation queue',
        'queue',
        'review queue',
        'admin review',
        'report',
        'reports',
        'user report',
        'user reports',
        'event report',
        'event reports',
        'comment report',
        'comment reports',
        'review report',
        'review reports',
        'reported content',
        'reported user',
        'reported users',
        'reported event',
        'reported events',
        'reported comment',
        'reported comments',
        'reported review',
        'reported reviews',
        'flag',
        'flags',
        'flagged',
        'flagged content',
        'flagged user',
        'flagged event',
        'flagged comment',
        'abuse',
        'abusive',
        'spam',
        'scam',
        'harassment',
        'inappropriate',
        'violation',
        'policy violation',
        'review report',
        'review reports',
        'open report',
        'open reports',
        'pending report',
        'pending reports',
        'resolve report',
        'resolve reports',
        'resolved report',
        'resolved reports',
        'reject report',
        'reject reports',
        'rejected report',
        'rejected reports',
        'dismiss report',
        'dismiss reports',
        'in review',
        'under review',
        'refund',
        'refunds',
        'refund request',
        'refund requests',
        'refund queue',
        'pending refund',
        'pending refunds',
        'approve refund',
        'approve refunds',
        'approved refund',
        'approved refunds',
        'reject refund',
        'reject refunds',
        'rejected refund',
        'rejected refunds',
        'resolve refund',
        'resolved refund',
        'refund decision',
        'refund decisions',
        'refund status',
        'paypal refund',
        'payment refund',
        'refund payment',
        'chargeback',
        'chargebacks',
        'moderator action',
        'moderation note',
        'decision note',
      ],
    ),
    AdminSearchResult(
      page: AdminShellPage.settings,
      title: 'Settings',
      description: 'Manage desktop application settings',
      icon: Icons.settings_outlined,
      keywords: [
        'setting',
        'settings',
        'manage settings',
        'application settings',
        'app settings',
        'desktop settings',
        'configuration',
        'config',
        'preferences',
        'preference',
        'customize',
        'customization',
        'appearance',
        'theme',
        'themes',
        'light theme',
        'dark theme',
        'dark mode',
        'light mode',
        'display',
        'interface',
        'user interface',
        'ui',
        'language',
        'locale',
        'notifications',
        'notification',
        'privacy',
        'security',
        'account settings',
        'system settings',
      ],
    ),
  ];
}