<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CloudinaryDotNet" Version="1.29.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.13" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.13">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.13">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="MassTransit" Version="8.3.6" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="8.3.6" />
	</ItemGroup>

	<ItemGroup>
    <ProjectReference Include="..\EventService.Application\EventService.Application.csproj" />
    <ProjectReference Include="..\..\Shared.Contracts\Shared.Contracts\Shared.Contracts.csproj" />
  </ItemGroup>

	<PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
