<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8fd137b3-d6b2-4a9b-a357-8292cfcbcf21</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MassTransit" Version="8.3.6" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="8.3.6" />
		<PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.3.6" />
	</ItemGroup>

	<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.13" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.13" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UserService.Application\UserService.Application.csproj" />
    <ProjectReference Include="..\UserService.Infrastructure\UserService.Infrastructure.csproj" />
  </ItemGroup>

    <ItemGroup>
		<PackageReference Include="DotNetEnv" Version="3.1.1" />
	</ItemGroup>

</Project>
